# path to the default data directory
data_path: ""
# option to enable nested progress bars
enable_nested_progress_bar: false
# dictionary containing parameters passed to the SpecsAnalyzer. Will be completed by the SpecsAnalyzer default config parameters
spa_params:
  apply_fft_filter: false

# dictionary containing units for the respective axes
units:
  Angle: "degree"
  Ekin: "eV"
  delay: "fs"
  mirrorX: "steps"
  mirrorY: "steps"
  X: "mm"
  Y: "mm"
  Z: "mm"
  tilt: "degree"
  azimuth: "degree"
  polar: "degree"
  voltage: "V"
  temperature: "K"
