# path to the default data directory
data_path: "path/to/data"
# option to enable nested progress bars
enable_nested_progress_bar: false

# dictionary containing renaming rules for axis names (to change the name in the xarrays)
coordinate_mapping:
  Ekin: "energy"
  Angle: "angular1"
  polar: "angular2"
  tilt: "angular2"
  azimuth: "angular2"
  X: "spatial1"
  Y: "spatial1"
  Z: "spatial1"

# dictionary of corresponding NeXus paths for the different axes
coordinate_depends:
  Ekin: "/entry/instrument/electronanalyser/energydispersion/kinetic_energy"
  Angle: "/entry/instrument/electronanalyser/transformations/analyzer_dispersion"
  polar: "/entry/sample/transformations/sample_polar"
  tilt: "/entry/sample/transformations/sample_tilt"
  azimuth: "/entry/sample/transformations/sample_azimuth"
  X: "/entry/sample/transformations/trans_x"
  Y: "/entry/sample/transformations/trans_y"
  Z: "/entry/sample/transformations/trans_z"

# dictionary containing units for the respective axes
units:
  angular1: "degree"
  angular2: "degree"
  energy: "eV"
  delay: "fs"
  mirrorX: "steps"
  mirrorY: "steps"
  X: "mm"
  Y: "mm"
  Z: "mm"
  voltage: "V"

# URL of the epics archiver request engine
archiver_url: "http://__epicsarchiver_host__:17668/retrieval/data/getData.json?pv="
# dictionary containing axis names with Epics channels to request from the EPICS archiver
epics_channels:
  tempa: "trARPES:Carving:TEMP_RBV"
  x: "trARPES:Carving:TRX.RBV"
  y: "trARPES:Carving:TRY.RBV"
  z: "trARPES:Carving:TRZ.RBV"
  polar: "trARPES:Carving:THT.RBV"
  tilt: "trARPES:Carving:PHI.RBV"
  azimuth: "trARPES:Carving:OMG.RBV"
  drain_current: "trARPES:Sample:Measure"
  pressure: "trARPES:XGS600:PressureAC:P_RD"

# parameters for NeXus conversion
nexus:
  # the reader to use
  reader: "mpes"
  # the NeXus definition to use
  definition: "NXmpes"
  # additional input files, e.g. config and ELN files
  input_files: ["../specsscan/config/NXmpes_arpes_config.json"]

# parameters for the SpecsAnalyzer
spa_params:
  # path to SPECS calib2d file (provided together with your analyzer)
  calib2d_file: "../tests/data/phoibos150.calib2d"
  # number of pixels along the energy dispersing direction
  nx_pixel: 1376
  # number of pixels along the angle/spatially dispersing direction
  ny_pixel: 1024
  # pixel size in millimeters
  pixel_size: 0.00645
  # binning factor applied to the image
  binning: 4
  # magnification of the lens system used for imaging the detector
  magnification: 4.54
  # option for cropping the resulting xarrays
  crop: false
  # option to apply Fourier filtering
  apply_fft_filter: true
  # dictionary containing definition for Gaussian Fourier peaks to subtract.
  # each entry defines:
  #   amplitude: the normalized peak amplitude
  #   pos_x/pos_y: the peak position in Fourier plane pixels
  #   sigma_x/sigma_y: the peak width (standard deviation) along each direction
  fft_filter_peaks:
    - amplitude: 1
      pos_x: 79
      pos_y: 0
      sigma_x: 8
      sigma_y: 8
    - amplitude: 1
      pos_x: 176
      pos_y: 0
      sigma_x: 8
      sigma_y: 8
    - amplitude: 1
      pos_x: 0
      pos_y: 109
      sigma_x: 5
      sigma_y: 8
    - amplitude: 1
      pos_x: 78
      pos_y: 109
      sigma_x: 5
      sigma_y: 5
    - amplitude: 1
      pos_x: 175
      pos_y: 108
      sigma_x: 5
      sigma_y: 5
    - amplitude: 1
      pos_x: 254
      pos_y: 109
      sigma_x: 5
      sigma_y: 8
