name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        git lfs pull
        python -m pip install --upgrade pip
        pip install pycodestyle pylint mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 specsanalyzer tests 
    - name: pylint
      run: |
        python -m pylint --load-plugins=nomad.metainfo.pylint_plugin specsanalyzer tests 
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional specsanalyzer tests