name: python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        git lfs pull
        python -m pip install --upgrade pip
        pip install pycodestyle pylint mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731,W503 specsanalyzer tests 
    - name: pylint
      run: |
        python -m pylint --load-plugins=nomad.metainfo.pylint_plugin specsanalyzer tests 
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional specsanalyzer tests